# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jesse van der Heijden"
resume_title:                   "Front-end Developer"
resume_contact_email:           "jesse.vanderheijden@gmail.com"
resume_contact_telephone:       "+31636202395"
resume_contact_address:         "van Bossestraat 70-1, 1051KB Amsterdam"
resume_header_contact_info: "van Bossestraat 70-1, Amsterdam | +31636202395 | jesse.vanderheijden@gmail.com"
resume_header_intro: "<p>In coding I found a way to express my creativity and use my analytical thinking. I like to keep on learning and find new ways to build things. In the codaisseur academy I proved that I can absorb large amounts of information in a short time, now it is time for me to take it to the next level and start creating, building and hack more everyday. I hope to find a company which gives me the envorinment to do this.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/MokumJ"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jesse-van-der-heijden-11942114a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
